name: avtoraqam
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  logger: ^2.3.0
  iconly: ^1.0.1
  animated_bottom_navigation_bar: ^1.3.3
  ionicons: ^0.1.2
  http: ^1.2.1
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1
  rename: ^3.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
